server {
    listen *:443 ssl;
    server_name stage.tghf.insitechdev.ru;
    http2 on;

    resolver 8.8.8.8 1.1.1.1 valid=300s ipv4=on ipv6=on;
    resolver_timeout 30s;

    ssl_certificate /etc/letsencrypt/live/stage.tghf.insitechdev.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stage.tghf.insitechdev.ru/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/stage.tghf.insitechdev.ru/chain.pem;
    ssl_dhparam /etc/ssl/dhparams.pem;
    ssl_buffer_size 1400;
    ssl_ciphers TLS13-AES-128-GCM-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384;
    ssl_ecdh_curve X25519:P-256:P-384:P-224:P-521;
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:20m;
    ssl_session_tickets off;
    ssl_session_timeout 4h;
    ssl_stapling on;
    ssl_stapling_verify on;

    access_log /var/log/nginx/stage.tghf.insitechdev.ru-access.log geoip2;
    error_log /var/log/nginx/stage.tghf.insitechdev.ru-error.log;

    root /data/apps/stage.tghf.insitechdev.ru/release/public;
    index index.php;

    large_client_header_buffers 8 16k;
    client_max_body_size 100m;
    disable_symlinks off;

    # Статические файлы
    location ~ /\. { deny all; access_log off; }
    location ~* \.(?:jpg|jpeg|gif|png|ico|svg|svgz|js|css|less|eot|ttf|woff|otf|scss|swf|xml|wmv|html|htm|avi|ogg|ogv|webm|htc|mp4|flv)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control public;
    }

    # Основной блок
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # API с CORS для Telegram MiniApp
    location ^~ /api/ {
        add_header 'Access-Control-Allow-Origin' "$http_origin";
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin,Content-Type,Accept,Authorization,X-Organization-Uid,X-Localization';
        add_header 'Access-Control-Allow-Credentials' 'true';

        if ($request_method = OPTIONS) {
            return 204;
        }

       try_files $uri $uri/ /index.php?$args;
    }

    # PHP-FPM
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params_geoip2;
        #fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_index index.php;
        fastcgi_pass php-insitechdev;
    }
}