---
node_locale: "en_US.UTF-8"
user:
  user: "insitechdev"
  group: "insitechdev"
  uid: 2000
  gid: 2000
laravel_root_dir: "/data/apps/stage/hydroflex/telegram"
laravel_storage_dir: "/data/apps/stage/hydroflex/telegram/storage"
laravel_release_dir: "/data/apps/stage/hydroflex/telegram/release"
